baseURL = 'https://foretvivante.fr/'
defaultContentLanguage = 'fr'
title = 'Forêt Vivante'
disableKinds = ['taxonomy', 'term']
enableRobotsTXT = true

[params]
    Description = "Projet Forêt Vivante"
    Keywords = ["Thônes", "Tournette", "Montremont", "Talamarche", "Haute Savoie", "forêt", "sylviculture", "épicéa", "hêtre", "biodiversité", "association"]

[imaging]
    quality = 75
    resampleFilter = "Lanczos"
    anchor = "Smart"

[build]
    [build.buildStats]
        enable = true
    [[build.cachebusters]]
        source = 'assets/notwatching/hugo_stats\.json'
        target = 'css'
[module]
    [[module.mounts]]
        source = 'assets'
        target = 'assets'
    [[module.mounts]]
        disableWatch = true
        source = 'hugo_stats.json'
        target = 'assets/notwatching/hugo_stats.json'
