baseURL = 'https://example.org/'
defaultContentLanguage = 'fr'
title = 'Forêt Vivante'
disableKinds = ['taxonomy', 'term', 'section']
enableRobotsTXT = true

[params]
    Description = "Projet Forêt Vivante"
    Keywords = ["forêt", "Thônes", "Tournette", "Montremont", "Talamarche", "sylviculture", "épicéa", "hêtre", "biodiversité", "association"]

[imaging]
    quality = 75
    resampleFilter = "Lanczos"
    anchor = "Smart"

[build]
    [build.buildStats]
        enable = true
    [[build.cachebusters]]
        source = 'assets/notwatching/hugo_stats\.json'
        target = 'css'
    [[build.cachebusters]]
        source = '(postcss|tailwind)\.config\.js'
        target = 'css'
[module]
    [[module.mounts]]
        source = 'assets'
        target = 'assets'
    [[module.mounts]]
        disableWatch = true
        source = 'hugo_stats.json'
        target = 'assets/notwatching/hugo_stats.json'
